name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
    
    runs-on: macos-latest
    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'deploy@neuraxis-test.iam.gserviceaccount.com'     
      
